# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 389d4118900bf55b07b22515b0d8357fb654f7a02a4ad8a9684c3b5785fb92382fd054f95a9e8e63f9a7150ca8d57b53d98dbcc1fc5aaf19cb372c1dbc7113fa

test:
  secret_key_base: 29a511ff04c10a799976da6953336db1e1b930c1c68b63be2a4ee6c4c2eaeb0deb991fffc4ab9bbb61834137bc8c06a18db98e1ca96db0e6a15d737900d3deca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
